## Numpy Exercises

## Part - A

#### Make use of the following inbuilt api's
1. min
2. max
2. mean
3. argmin
4. argmax
5. linalg.solve
6. flatten
7. ravel
8. dot Product
9. \* for Matrix (Element wise multiplication)
10. arange followed by reshape
11. identity / eye
12. sum
13. diag
14. tril / triu

## Part - B

#### For the all api's mentioned above implement your own version of it. Except linalg.solve. At minimum each implementation of yours should support 2d matrices.


In [1]:
import numpy as np

In [2]:
mat_a = [[1,2,3],[4,5,6],[89,2,7]]
mat_a = np.array(mat_a)

In [3]:
mat_b = [[23,23],[1,2],[-90,-91]]
mat_b = np.array(mat_b)

## Minimum of the elements in a matrix

In [4]:
np.min(mat_a)


1

In [5]:
np.min(mat_b)

-91

In [8]:
def min_arr(a, min):
     for x in a:
            if (x<min):
                min = x
     return min
    

In [9]:
import math
def minimum(a):
    min = math.inf
    for k in a:
        min = min_arr(k,min)
    return min


In [10]:
minimum(mat_b)

-91

## Maximum of the elements in the matrix

In [11]:
np.max(mat_a)

89

In [12]:
np.max(mat_b)

23

In [13]:
def max_arr(a, max):
     for x in a:
            if (x>max):
                max= x
     return max
    

In [14]:
import math
def maximum(a):
    max = -(math.inf)
    for k in a:
        max = max_arr(k,max)
    return max


In [15]:
maximum(mat_a)

89

In [16]:
maximum(mat_b)

23

## Sum

In [17]:
def sum_arr(a):
    sum = 0
    for k in a:
        sum = sum+k
    return sum

In [18]:
def summation(a):
    sum = 0
    for k in a:
        sum = sum + sum_arr(k)
    return sum
    

In [19]:
summation(mat_a)

119

In [20]:
mat_a.sum()

119

In [21]:
summation(mat_b)

-132

In [22]:
mat_b.sum()

-132

## Mean

In [23]:
def mean_arr(a):
    return (summation(a)/a.size)

In [24]:
mean_arr(mat_a)

13.222222222222221

In [25]:
mean_arr(mat_b)


-22.0

In [26]:
mat_a.mean()

13.222222222222221

In [27]:
mat_b.mean()

-22.0

## Argmin

In [28]:
def return_min_index(a):
    min = math.inf
    counter = 0
    for k in a:
        if k < min:
            min = k
            index = counter
        counter +=1
    return index
            

In [29]:
def arg_min(a, axis):
    index =[]
    if(axis==1):
        for k in a:
            index.append(return_min_index(k))
    return index

In [30]:
arg_min(mat_a, axis=1)

[0, 0, 1]

In [31]:
mat_a.argmin(axis=1)

array([0, 0, 1])

## Argmax

In [32]:
def return_max_index(a):
    max = -math.inf
    counter = 0
    for k in a:
        if k > max:
            max = k
            index = counter
        counter +=1
    return index
            

In [33]:
def arg_max(a, axis):
    index =[]
    if(axis==1):
        for k in a:
            index.append(return_max_index(k))
    return index

In [35]:
arg_max(mat_a, axis=1)

[2, 2, 0]

In [36]:
mat_a.argmax(axis=1)

array([2, 2, 0])

## Linalg.solve

In [37]:
np.linalg.solve(mat_a, mat_b)

array([[ -2.86594203,  -2.84782609],
       [-39.26811594, -38.30434783],
       [ 34.80072464,  34.15217391]])

## Flatten

In [40]:
mat_a.flatten()

array([ 1,  2,  3,  4,  5,  6, 89,  2,  7])

In [59]:
def mat_flat(a):
    r=[]
    for item in a:
        for word in item:
            r.append(word)
    return r
    

In [60]:
mat_flat(mat_a)

[1, 2, 3, 4, 5, 6, 89, 2, 7]

## Ravel

In [61]:
np.ravel(mat_a)

array([ 1,  2,  3,  4,  5,  6, 89,  2,  7])

In [62]:
def mat_ravel(a):
    r=[]
    for item in a:
        for word in item:
            r.append(word)
    return r

In [63]:
mat_ravel(mat_a)

[1, 2, 3, 4, 5, 6, 89, 2, 7]

## Dot product

In [64]:
mat_a.dot(mat_b)

array([[-245, -246],
       [-443, -444],
       [1419, 1414]])

In [71]:
import numpy as nd
result = np.array([[0,0],[0,0],[0,0]])
for i in range(len(mat_a)):
    for j in range(len(mat_b[0])):
        for k in range(len(mat_b)):
            result[i][j] += mat_a[i][k] * mat_b[k][j]

print("without using inbuilt api")
for r in result:
    print(r)
    
        

without using inbuilt api
[-245 -246]
[-443 -444]
[1419 1414]


## Element wise multiplication

In [81]:
mat_b = [[23,23,23],[1,2,3],[-90,-91,-9]]
mat_b = np.array(mat_b)
mat_b.shape

(3, 3)

In [82]:
    
print("by using inbuilt api")
np.multiply(mat_a,mat_b)

by using inbuilt api


array([[   23,    46,    69],
       [    4,    10,    18],
       [-8010,  -182,   -63]])

In [84]:
result = ([[0,0,0],[0,0,0],[0,0,0]])
a_rows,a_cols = mat_a.shape
for i in range(a_rows):
    for j in range(a_cols):
        result[i][j] = mat_a[i][j]*mat_b[i][j]
print("without using api")
for k in result:
    print(k)
    


without using api
[23, 46, 69]
[4, 10, 18]
[-8010, -182, -63]


## Identity matrix

In [88]:
iden_a = np.identity(3)
print(iden_a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [87]:
b = np.empty(a.size)
s = 0
a_rows, a_cols = mat_a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i == j:
            b[s] = 1
            s += 1
        else:
            b[s] = 0
            s += 1
print("without using inbuilt api diagonal array is\n",b.reshape(3,3))


without using inbuilt api diagonal array is
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Arange and reshape- Diagonal elements

In [90]:
a_arange_reshape = np.arange(9).reshape(3,3)
print(a_arange_reshape)
print("diagonal array is diagonal array is",np.diag(a_arange_reshape))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
diagonal array is diagonal array is [0 4 8]


In [92]:
b_arange_reshape = np.random.random(3)
s = 0
a_rows, a_cols = mat_a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i == j:
           b_arange_reshape[s] = a[i,j]
           s += 1
print("without using inbuilt api diagonal array is",b_arange_reshape)


without using inbuilt api diagonal array is [ 0.  4.  8.]
